const GET_MODELS = "GET_MODELS";
const FILTER_PICKUPS = "FILTER_PICKUPS";
const FILTER_SUVS = "FILTER_SUVS";
const FILTER_AUTOS = "FILTER_AUTOS";
const PRICE_AND_YEAR_ORDER = "PRICE_AND_YEAR_ORDER";
const MODEL_DETAIL = "MODEL_DETAIL"

export {
  GET_MODELS,
  FILTER_PICKUPS,
  FILTER_SUVS,
  FILTER_AUTOS,
  PRICE_AND_YEAR_ORDER,
  MODEL_DETAIL
};